version: '3'
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "6100:8000"
    depends_on:
      - postgres